### PR TITLE
updated R file that controls UI text

### PR DESCRIPTION
**Pull request by JSchripsema-IDM**

### CODE REVIEW

**Review by DKong-IDM — COMMENTED** [review]
the <code> tag will not be rendered properly inside the p() function. You can change the p() to HTML() and the code tag should be rendered properly.

**Comment by JSchripsema-IDM** [comment]
> 
> 
> the ` tag will not be rendered properly inside the p() function. You can change the p() to HTML() and the code tag should be rendered properly.`

Fixed!

**Review by DKong-IDM — APPROVED** [review]
Looks good!

**Comment by JHerbeck-IDM** [comment]
Looks great, thank you!

**Pull request merged**
